/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Azure RTOS GUIX Studio application and re-generating the application   */
/*  resource file(s). For more information please refer to the Azure RTOS GUIX */
/*  Studio User Guide, or visit our web site at azure.com/rtos                 */
/*                                                                             */
/*  GUIX Studio Revision 6.1.0.0                                               */
/*  Date (dd.mm.yyyy): 13.11.2020   Time (hh:mm): 10:10                        */
/*******************************************************************************/


#include "gx_api.h"
#include "guiapp_resources.h"

/* Color Table                                                                 */

GX_CONST GX_COLOR display_1_theme_1_color_table[] =
{
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000001,
    0x00000001,
    0x00000001,
    0x00000001,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000001,
    0x00000000,
    0x00000000,
    0x00000001,
    0x00000000,
    0x00000000,
    0x00000001,
    0x00000000,
    0x00000001,
    0x00000000,
    0x00000000,
    0x00000001,
    0x00000000,
    0x00000001,
    0x00000001,
    0x00000001,
    0x00000000,
    0x00000001,
    0x00000000
};

GX_CONST GX_COLOR display_1_theme_2_color_table[] =
{
    0x00000001,
    0x00000001,
    0x00000001,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000001,
    0x00000001,
    0x00000001,
    0x00000000,
    0x00000001,
    0x00000001,
    0x00000000,
    0x00000001,
    0x00000001,
    0x00000000,
    0x00000001,
    0x00000000,
    0x00000001,
    0x00000001,
    0x00000000,
    0x00000001,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000001,
    0x00000000,
    0x00000001
};


/* Font Table                                                                  */


extern GX_FONT _gx_system_font_mono;
GX_CONST GX_FONT *display_1_theme_1_font_table[] =
{
    &_gx_system_font_mono,
    &_gx_system_font_mono,
    &_gx_system_font_mono,
    &_gx_system_font_mono
};
GX_CONST GX_FONT *display_1_theme_2_font_table[] =
{
    &_gx_system_font_mono,
    &_gx_system_font_mono,
    &_gx_system_font_mono,
    &_gx_system_font_mono
};

/* Pixelmap data definitions                                                   */


/* THEME_1_RADIO_ON pixelmap data                                              */

static GX_CONST GX_UBYTE DISPLAY_1_THEME_1_RADIO_ON_pixelmap_data[64] =
{
    0x00, 0xf5, 0x5c, 0x00, 0x03, 0x7f, 0xfd, 0xc0, 0x0f, 0xfd, 0x7f, 0x70, 0x3f, 
    0xd5, 0x57, 0xdc, 0x1f, 0x55, 0x55, 0xf4, 0xfd, 0x55, 0x55, 0x7f, 0x7d, 0x55, 
    0x55, 0x7f, 0x75, 0x55, 0x55, 0x5d, 0x75, 0x55, 0x55, 0x5d, 0x7d, 0x55, 0x55, 
    0x5f, 0xfd, 0x55, 0x55, 0x7f, 0x1f, 0x55, 0x55, 0xf4, 0x3f, 0xd5, 0x57, 0xdc, 
    0x0f, 0xfd, 0x7f, 0x70, 0x03, 0x7f, 0xfd, 0xc0, 0x00, 0x35, 0x5c, 0x00
};
GX_CONST GX_PIXELMAP DISPLAY_1_THEME_1_RADIO_ON_pixelmap =
{
    0x00000001,                              /* major version                  */
    0x00000000,                              /* minor version                  */
    GX_PIXELMAP_TRANSPARENT,                 /* flags                          */
    GX_COLOR_FORMAT_MONOCHROME,              /* Format                         */
    (GX_UBYTE *) DISPLAY_1_THEME_1_RADIO_ON_pixelmap_data,
    sizeof(DISPLAY_1_THEME_1_RADIO_ON_pixelmap_data),    /* the size of pixelmap_data*/
    NULL,
    0,                                       /* auxiliary data size            */
    0x00,                                    /* used for transparent iamges    */
    16,                                      /* width in pixel                 */
    16                                       /* height in pixel                */
};

/* THEME_1_RADIO_OFF pixelmap data                                             */

static GX_CONST GX_UBYTE DISPLAY_1_THEME_1_RADIO_OFF_pixelmap_data[64] =
{
    0x00, 0xd5, 0x54, 0x00, 0x01, 0x55, 0x55, 0x00, 0x05, 0x5f, 0xf5, 0x50, 0x15, 
    0xff, 0xff, 0x50, 0x17, 0xff, 0xff, 0xd4, 0x57, 0xff, 0xff, 0xd5, 0x5f, 0xff, 
    0xff, 0xf5, 0x5f, 0xff, 0xff, 0xf5, 0x5f, 0xff, 0xff, 0xf5, 0x5f, 0xff, 0xff, 
    0xf5, 0x57, 0xff, 0xff, 0xd5, 0x17, 0xff, 0xff, 0xd4, 0x15, 0xff, 0xff, 0x50, 
    0x05, 0x5f, 0xf5, 0x50, 0x01, 0x55, 0x55, 0xc0, 0x00, 0x15, 0x54, 0x00
};
GX_CONST GX_PIXELMAP DISPLAY_1_THEME_1_RADIO_OFF_pixelmap =
{
    0x00000001,                              /* major version                  */
    0x00000000,                              /* minor version                  */
    GX_PIXELMAP_TRANSPARENT,                 /* flags                          */
    GX_COLOR_FORMAT_MONOCHROME,              /* Format                         */
    (GX_UBYTE *) DISPLAY_1_THEME_1_RADIO_OFF_pixelmap_data,
    sizeof(DISPLAY_1_THEME_1_RADIO_OFF_pixelmap_data),    /* the size of pixelmap_data*/
    NULL,
    0,                                       /* auxiliary data size            */
    0x00,                                    /* used for transparent iamges    */
    16,                                      /* width in pixel                 */
    16                                       /* height in pixel                */
};

/* THEME_1_CHECKBOX_ON pixelmap data                                           */

static GX_CONST GX_UBYTE DISPLAY_1_THEME_1_CHECKBOX_ON_pixelmap_data[32] =
{
    0x00, 0x00, 0x7f, 0xfc, 0x7f, 0xfe, 0x7f, 0xfe, 0x7f, 0xee, 0x7f, 0xce, 0x77, 
    0x8e, 0x73, 0x1e, 0x72, 0x1e, 0x70, 0x3e, 0x78, 0x7c, 0x7d, 0xfc, 0x7f, 0xfc, 
    0x7f, 0xfe, 0x3f, 0xc4, 0x00, 0x00
};
GX_CONST GX_PIXELMAP DISPLAY_1_THEME_1_CHECKBOX_ON_pixelmap =
{
    0x00000001,                              /* major version                  */
    0x00000000,                              /* minor version                  */
    0,                                       /* flags                          */
    GX_COLOR_FORMAT_MONOCHROME,              /* Format                         */
    (GX_UBYTE *) DISPLAY_1_THEME_1_CHECKBOX_ON_pixelmap_data,
    sizeof(DISPLAY_1_THEME_1_CHECKBOX_ON_pixelmap_data),    /* the size of pixelmap_data*/
    NULL,
    0,                                       /* auxiliary data size            */
    0x00,                                    /* used for transparent iamges    */
    16,                                      /* width in pixel                 */
    16                                       /* height in pixel                */
};

/* THEME_1_CHECKBOX_OFF pixelmap data                                          */

static GX_CONST GX_UBYTE DISPLAY_1_THEME_1_CHECKBOX_OFF_pixelmap_data[32] =
{
    0x00, 0x00, 0x7f, 0xfc, 0x7f, 0xfe, 0x7f, 0xfc, 0x7f, 0xfc, 0x7f, 0xfc, 0x7f, 
    0xfc, 0x7f, 0xfc, 0x7f, 0xfc, 0x7f, 0xfc, 0x7f, 0xfc, 0x7f, 0xfc, 0x7f, 0xfc, 
    0x7f, 0xfc, 0x20, 0x00, 0x00, 0x00
};
GX_CONST GX_PIXELMAP DISPLAY_1_THEME_1_CHECKBOX_OFF_pixelmap =
{
    0x00000001,                              /* major version                  */
    0x00000000,                              /* minor version                  */
    0,                                       /* flags                          */
    GX_COLOR_FORMAT_MONOCHROME,              /* Format                         */
    (GX_UBYTE *) DISPLAY_1_THEME_1_CHECKBOX_OFF_pixelmap_data,
    sizeof(DISPLAY_1_THEME_1_CHECKBOX_OFF_pixelmap_data),    /* the size of pixelmap_data*/
    NULL,
    0,                                       /* auxiliary data size            */
    0x00,                                    /* used for transparent iamges    */
    16,                                      /* width in pixel                 */
    16                                       /* height in pixel                */
};

/* THEME_1_YXYL_LOGO pixelmap data                                             */

static GX_CONST GX_UBYTE DISPLAY_1_THEME_1_YXYL_LOGO_pixelmap_data[785] =
{
    0xff, 0xff, 0xe7, 0xa1, 0xf3, 0xff, 0xff, 0xd7, 0xbd, 0xe7, 0xff, 0xff, 0xcf, 
    0xcd, 0xdf, 0xff, 0xff, 0xc7, 0xdd, 0xd7, 0xff, 0xff, 0xc3, 0xe5, 0xd3, 0xff, 
    0xff, 0xbf, 0xa5, 0xa3, 0xa1, 0xcf, 0xff, 0xff, 0xbb, 0x9d, 0xbb, 0x99, 0xcb, 
    0xff, 0xff, 0xb7, 0x99, 0xc7, 0x99, 0xc7, 0xff, 0xff, 0xb3, 0x99, 0xd3, 0x95, 
    0xc3, 0xff, 0xfb, 0xa1, 0x93, 0x91, 0xdf, 0x95, 0xbf, 0xff, 0xef, 0xb9, 0x03, 
    0x91, 0xe3, 0x95, 0xbf, 0xff, 0xe7, 0xd9, 0xe7, 0x95, 0xbb, 0xff, 0xdf, 0xdd, 
    0xef, 0x91, 0xbb, 0xff, 0xdb, 0xad, 0x03, 0xa9, 0xf3, 0x95, 0xb7, 0xff, 0xd7, 
    0x9d, 0xab, 0x91, 0xfb, 0x91, 0xb7, 0xff, 0xd3, 0x99, 0xbb, 0x89, 0xfb, 0x91, 
    0xb7, 0xff, 0xcf, 0x99, 0xc3, 0x01, 0xff, 0x91, 0xb7, 0xff, 0xcb, 0x95, 0xf7, 
    0x01, 0xd7, 0x91, 0xb3, 0xff, 0xc7, 0x95, 0xf7, 0x89, 0xd3, 0x9d, 0xa7, 0xff, 
    0xc7, 0x91, 0xfb, 0x89, 0xd3, 0xa5, 0x9f, 0xff, 0xc3, 0x95, 0xf3, 0x99, 0xcb, 
    0xa9, 0x9b, 0xff, 0xbf, 0x95, 0xf7, 0x99, 0xd7, 0xa5, 0x93, 0xff, 0xbf, 0x91, 
    0xff, 0x03, 0x89, 0xeb, 0x9d, 0x8f, 0xff, 0xbb, 0x95, 0xff, 0x0f, 0x03, 0x01, 
    0x01, 0xf3, 0x95, 0x8f, 0xff, 0xbb, 0x91, 0xff, 0xff, 0x8b, 0x95, 0x8b, 0x97, 
    0x95, 0xd3, 0x89, 0x9b, 0x0d, 0x01, 0x03, 0x03, 0x91, 0xe7, 0x89, 0x93, 0x89, 
    0xab, 0x05, 0x01, 0xc7, 0x95, 0x07, 0x03, 0x8f, 0xa5, 0xcb, 0x8d, 0x93, 0x8d, 
    0xff, 0x89, 0x8f, 0x8d, 0xa7, 0x8d, 0xc7, 0x91, 0x07, 0x03, 0x8b, 0xad, 0xc3, 
    0x91, 0x93, 0x8d, 0xfb, 0x91, 0x8b, 0x91, 0xa3, 0x8d, 0xcb, 0x91, 0x03, 0x07, 
    0x03, 0xb5, 0xbf, 0x91, 0x93, 0x8d, 0xfb, 0x91, 0x8b, 0x91, 0xa3, 0x8d, 0xcb, 
    0x91, 0x03, 0x03, 0x95, 0x8f, 0x91, 0x9b, 0x89, 0x97, 0x91, 0x93, 0x8d, 0x9b, 
    0x89, 0xaf, 0x89, 0x97, 0x91, 0x8b, 0xa5, 0x8f, 0x8d, 0x03, 0x89, 0xbf, 0x8d, 
    0x03, 0x03, 0x8d, 0x9b, 0x8d, 0x8f, 0x9d, 0x8f, 0x91, 0x93, 0x8d, 0x93, 0x99, 
    0x9b, 0x9d, 0x8f, 0x91, 0x8b, 0xa9, 0x8b, 0xa9, 0xb3, 0x91, 0x91, 0xb7, 0xa5, 
    0x8b, 0x91, 0x93, 0x8d, 0x8f, 0xa5, 0x8f, 0xa5, 0x8b, 0x91, 0x8b, 0xa9, 0x8b, 
    0xad, 0xaf, 0x91, 0x8d, 0xb7, 0xad, 0x07, 0x03, 0x91, 0x03, 0x89, 0x03, 0x8d, 
    0x8b, 0xa9, 0x8b, 0xad, 0x07, 0x03, 0x91, 0x8b, 0xa5, 0x8f, 0xb1, 0xab, 0x91, 
    0x8d, 0xb7, 0x91, 0x07, 0x03, 0x95, 0x03, 0xb5, 0x07, 0x03, 0x91, 0x07, 0x03, 
    0x91, 0x8b, 0x91, 0x07, 0x03, 0x95, 0x03, 0x91, 0x8b, 0x91, 0xa3, 0x95, 0x07, 
    0x03, 0x91, 0xab, 0x91, 0x8d, 0xb3, 0x91, 0x93, 0x8d, 0x03, 0xb5, 0x07, 0x03, 
    0x8d, 0x07, 0x03, 0x91, 0x8f, 0x8d, 0x93, 0x8d, 0x03, 0x91, 0x8b, 0x91, 0xa3, 
    0x8d, 0x93, 0x8d, 0xab, 0x91, 0x8d, 0xb3, 0x8d, 0x97, 0x8d, 0x03, 0xb5, 0x07, 
    0x03, 0x8d, 0x03, 0x91, 0x8f, 0x8d, 0x97, 0x8d, 0x03, 0x91, 0x8b, 0x91, 0xa3, 
    0x8d, 0x97, 0x8d, 0xa7, 0x91, 0x91, 0xaf, 0x8d, 0x97, 0x8d, 0x03, 0xb5, 0x07, 
    0x03, 0xa1, 0x13, 0x01, 0x01, 0x03, 0x03, 0x8d, 0x97, 0x8d, 0x03, 0x91, 0x8b, 
    0x91, 0xa3, 0x8d, 0x97, 0x8d, 0xa7, 0x91, 0x03, 0x8d, 0x9b, 0x8d, 0x03, 0x91, 
    0x93, 0x8d, 0x03, 0x91, 0x93, 0x8d, 0x07, 0x03, 0x99, 0x07, 0x03, 0x8d, 0x03, 
    0x91, 0x93, 0x8d, 0x03, 0x91, 0x8f, 0x8d, 0xa3, 0x8d, 0x97, 0x8d, 0xa3, 0x95, 
    0x03, 0x95, 0x8f, 0x91, 0x07, 0x03, 0x91, 0x8b, 0x91, 0x03, 0x91, 0x93, 0x8d, 
    0x07, 0x03, 0x95, 0x07, 0x03, 0x91, 0x07, 0x03, 0x91, 0x8b, 0x91, 0x03, 0x91, 
    0x8f, 0x91, 0x8b, 0x8d, 0x03, 0x8d, 0x97, 0x8d, 0xa3, 0x91, 0x03, 0x07, 0x03, 
    0xb5, 0x07, 0x03, 0xad, 0x07, 0x03, 0x91, 0x93, 0x8d, 0x8b, 0xad, 0x07, 0x03, 
    0xb1, 0x07, 0x03, 0x95, 0x07, 0x03, 0xad, 0x03, 0x8d, 0x97, 0x8d, 0xa3, 0x91, 
    0x03, 0x8b, 0xad, 0x8f, 0xa5, 0x8b, 0x91, 0x93, 0x8d, 0x8b, 0xa9, 0x8f, 0xad, 
    0x07, 0x03, 0x99, 0x07, 0x03, 0xa9, 0x03, 0x8d, 0x97, 0x8d, 0x9f, 0x95, 0x03, 
    0x8f, 0xa5, 0x97, 0x9d, 0x93, 0x8d, 0x93, 0x8d, 0x8f, 0xa1, 0x97, 0xa9, 0x8b, 
    0x95, 0x8b, 0xa1, 0x07, 0x03, 0x8d, 0x97, 0x8d, 0x9f, 0x91, 0x07, 0x03, 0x97, 
    0x95, 0xa7, 0x91, 0x97, 0x89, 0x9b, 0x05, 0x01, 0x9b, 0x91, 0xa7, 0x91, 0x0b, 
    0x01, 0x01, 0x93, 0x8d, 0x97, 0x91, 0x93, 0x05, 0x01, 0x9b, 0x89, 0x9f, 0x95, 
    0x07, 0x03, 0xff, 0xff, 0xff, 0xdb, 0x95, 0x8b, 0xff, 0x9b, 0x95, 0x9f, 0x01, 
    0x9f, 0x0d, 0x03, 0x03, 0x01, 0xa7, 0x01, 0x9b, 0x95, 0x9b, 0x01, 0x9f, 0x8d, 
    0x07, 0x01, 0x97, 0x95, 0x8f, 0xff, 0x9b, 0x95, 0x9f, 0x01, 0x9b, 0x99, 0x9f, 
    0x01, 0x97, 0x95, 0x9f, 0x01, 0x9f, 0x95, 0x93, 0x95, 0x93, 0xff, 0xd3, 0x01, 
    0x9f, 0x09, 0x03, 0x01, 0xab, 0x01, 0x97, 0x95, 0x9f, 0x01, 0x9f, 0x95, 0x8b, 
    0x99, 0x97, 0xff, 0x97, 0x99, 0x9f, 0x01, 0x9b, 0x8d, 0x07, 0x01, 0xa3, 0x01, 
    0x97, 0x99, 0x9b, 0x01, 0x9f, 0x95, 0x07, 0x03, 0x99, 0x9b, 0xff, 0x9f, 0x0d, 
    0x03, 0x03, 0x01, 0xa3, 0x01, 0x9b, 0x05, 0x03, 0x91, 0x9f, 0x01, 0x97, 0x05, 
    0x03, 0x8d, 0x9f, 0x01, 0x9f, 0x91, 0x8b, 0x95, 0x9f, 0xff, 0x9b, 0x01, 0x8b, 
    0x05, 0x01, 0x9f, 0x01, 0x9b, 0x11, 0x03, 0x01, 0x03, 0x01, 0xa7, 0x01, 0x97, 
    0x89, 0x0f, 0x03, 0x01, 0x01, 0x9b, 0x01, 0x9b, 0x99, 0x07, 0x03, 0x8d, 0xa7, 
    0xff, 0x9b, 0x95, 0x9f, 0x01, 0xa3, 0x89, 0xa7, 0x01, 0x9b, 0x95, 0x9b, 0x01, 
    0xa3, 0x89, 0x07, 0x01, 0xbf
};
GX_CONST GX_PIXELMAP DISPLAY_1_THEME_1_YXYL_LOGO_pixelmap =
{
    0x00000001,                              /* major version                  */
    0x00000000,                              /* minor version                  */
    GX_PIXELMAP_COMPRESSED|GX_PIXELMAP_TRANSPARENT,         /* flags           */
    GX_COLOR_FORMAT_MONOCHROME,              /* Format                         */
    (GX_UBYTE *) DISPLAY_1_THEME_1_YXYL_LOGO_pixelmap_data,
    sizeof(DISPLAY_1_THEME_1_YXYL_LOGO_pixelmap_data),    /* the size of pixelmap_data*/
    NULL,
    0,                                       /* auxiliary data size            */
    0x00,                                    /* used for transparent iamges    */
    128,                                     /* width in pixel                 */
    51                                       /* height in pixel                */
};

/* Pixelmap Table                                                              */


GX_CONST GX_PIXELMAP *display_1_theme_1_pixelmap_table[] =
{
    GX_NULL,
    &DISPLAY_1_THEME_1_RADIO_ON_pixelmap,
    &DISPLAY_1_THEME_1_RADIO_OFF_pixelmap,
    &DISPLAY_1_THEME_1_CHECKBOX_ON_pixelmap,
    &DISPLAY_1_THEME_1_CHECKBOX_OFF_pixelmap,
    &DISPLAY_1_THEME_1_YXYL_LOGO_pixelmap
};
GX_CONST GX_PIXELMAP *display_1_theme_2_pixelmap_table[] =
{
    GX_NULL,
    &DISPLAY_1_THEME_1_RADIO_ON_pixelmap,
    &DISPLAY_1_THEME_1_RADIO_OFF_pixelmap,
    &DISPLAY_1_THEME_1_CHECKBOX_ON_pixelmap,
    &DISPLAY_1_THEME_1_CHECKBOX_OFF_pixelmap,
    &DISPLAY_1_THEME_1_YXYL_LOGO_pixelmap
};

/* String values                                                               */

GX_CONST GX_UBYTE display_1_STRING_1_English[] = "text_view";
GX_CONST GX_UBYTE display_1_STRING_2_English[] = "prompt";
GX_CONST GX_UBYTE display_1_STRING_3_English[] = "www.armbbs.cn";
GX_CONST GX_UBYTE display_1_STRING_4_English[] = "button";
GX_CONST GX_UBYTE display_1_STRING_5_English[] = "ARMFLY";
GX_CONST GX_UBYTE display_1_STRING_6_English[] = "The First Window";
GX_CONST GX_UBYTE display_1_STRING_7_English[] = "The Second Window";
GX_CONST GX_UBYTE display_1_STRING_8_English[] = "The Third Window";
GX_CONST GX_UBYTE display_1_STRING_9_English[] = "armfly";
GX_CONST GX_UBYTE display_1_STRING_10_English[] = "armbbs";

/* String Table for display_1 language English                                 */

GX_CONST GX_STRING display_1_English_string_table[11] =
{
    {GX_NULL, 0},
    {(GX_CONST GX_CHAR *)display_1_STRING_1_English, sizeof(display_1_STRING_1_English) - 1},
    {(GX_CONST GX_CHAR *)display_1_STRING_2_English, sizeof(display_1_STRING_2_English) - 1},
    {(GX_CONST GX_CHAR *)display_1_STRING_3_English, sizeof(display_1_STRING_3_English) - 1},
    {(GX_CONST GX_CHAR *)display_1_STRING_4_English, sizeof(display_1_STRING_4_English) - 1},
    {(GX_CONST GX_CHAR *)display_1_STRING_5_English, sizeof(display_1_STRING_5_English) - 1},
    {(GX_CONST GX_CHAR *)display_1_STRING_6_English, sizeof(display_1_STRING_6_English) - 1},
    {(GX_CONST GX_CHAR *)display_1_STRING_7_English, sizeof(display_1_STRING_7_English) - 1},
    {(GX_CONST GX_CHAR *)display_1_STRING_8_English, sizeof(display_1_STRING_8_English) - 1},
    {(GX_CONST GX_CHAR *)display_1_STRING_9_English, sizeof(display_1_STRING_9_English) - 1},
    {(GX_CONST GX_CHAR *)display_1_STRING_10_English, sizeof(display_1_STRING_10_English) - 1}
};

/*  Language Table                                                             */


GX_CONST GX_STRING *display_1_language_table[1] = 
{
    display_1_English_string_table,
};

GX_THEME display_1_theme_1 =
{
    (GX_COLOR *) display_1_theme_1_color_table,
    (GX_FONT **) display_1_theme_1_font_table,
    (GX_PIXELMAP **) display_1_theme_1_pixelmap_table,
    NULL,
    {
        20,                                  /* scroll width                   */
        18,                                  /* thumb width                    */
        20,                                  /* thumb travel min               */
        20,                                  /* thumb travel max               */
        4,                                   /* thumb border style             */
        0,                                   /* scroll fill pixelmap           */
        0,                                   /* scroll thumb pixelmap          */
        0,                                   /* scroll up pixelmap             */
        0,                                   /* scroll down pixelmap           */
        GX_COLOR_ID_SCROLL_BUTTON,           /* scroll thumb color             */
        GX_COLOR_ID_SCROLL_BUTTON,           /* scroll thumb border color      */
        GX_COLOR_ID_SCROLL_BUTTON,           /* scroll button color            */
    },
    {
        20,                                  /* scroll width                   */
        18,                                  /* thumb width                    */
        20,                                  /* thumb travel min               */
        20,                                  /* thumb travel max               */
        4,                                   /* thumb border style             */
        0,                                   /* scroll fill pixelmap           */
        0,                                   /* scroll thumb pixelmap          */
        0,                                   /* scroll up pixelmap             */
        0,                                   /* scroll down pixelmap           */
        GX_COLOR_ID_SCROLL_BUTTON,           /* scroll thumb color             */
        GX_COLOR_ID_CANVAS,                  /* scroll thumb border color      */
        GX_COLOR_ID_SCROLL_BUTTON,           /* scroll button color            */
    },
    GX_SCROLLBAR_RELATIVE_THUMB|GX_SCROLLBAR_END_BUTTONS|GX_SCROLLBAR_VERTICAL,
    GX_SCROLLBAR_RELATIVE_THUMB|GX_SCROLLBAR_END_BUTTONS|GX_SCROLLBAR_HORIZONTAL,
    29,                                      /* color table size               */
    4,                                       /* font table size                */
    6,                                       /* pixelmap table size            */
    0                                        /* palette size                   */

};

GX_THEME display_1_theme_2 =
{
    (GX_COLOR *) display_1_theme_2_color_table,
    (GX_FONT **) display_1_theme_2_font_table,
    (GX_PIXELMAP **) display_1_theme_2_pixelmap_table,
    NULL,
    {
        20,                                  /* scroll width                   */
        18,                                  /* thumb width                    */
        20,                                  /* thumb travel min               */
        20,                                  /* thumb travel max               */
        4,                                   /* thumb border style             */
        0,                                   /* scroll fill pixelmap           */
        0,                                   /* scroll thumb pixelmap          */
        0,                                   /* scroll up pixelmap             */
        0,                                   /* scroll down pixelmap           */
        GX_COLOR_ID_SCROLL_BUTTON,           /* scroll thumb color             */
        GX_COLOR_ID_SCROLL_BUTTON,           /* scroll thumb border color      */
        GX_COLOR_ID_SCROLL_BUTTON,           /* scroll button color            */
    },
    {
        20,                                  /* scroll width                   */
        18,                                  /* thumb width                    */
        20,                                  /* thumb travel min               */
        20,                                  /* thumb travel max               */
        4,                                   /* thumb border style             */
        0,                                   /* scroll fill pixelmap           */
        0,                                   /* scroll thumb pixelmap          */
        0,                                   /* scroll up pixelmap             */
        0,                                   /* scroll down pixelmap           */
        GX_COLOR_ID_SCROLL_BUTTON,           /* scroll thumb color             */
        GX_COLOR_ID_CANVAS,                  /* scroll thumb border color      */
        GX_COLOR_ID_SCROLL_BUTTON,           /* scroll button color            */
    },
    GX_SCROLLBAR_RELATIVE_THUMB|GX_SCROLLBAR_END_BUTTONS|GX_SCROLLBAR_VERTICAL,
    GX_SCROLLBAR_RELATIVE_THUMB|GX_SCROLLBAR_END_BUTTONS|GX_SCROLLBAR_HORIZONTAL,
    29,                                      /* color table size               */
    4,                                       /* font table size                */
    6,                                       /* pixelmap table size            */
    0                                        /* palette size                   */

};
GX_CONST GX_THEME *display_1_theme_table[2] =
{
    &display_1_theme_1,
    &display_1_theme_2
};

